$query = "SELECT TOP (1000) [AppModelId]
,[InternalId]
,[ProgramId]
,[ProductName]
,[ProductVersion]
,[Publisher]
,[ProductLanguage]
,[ProductCode]
,[IsDeleted]
,[SequenceNumber]
FROM [dbo].[vCMGS_AppProgramSyncData]"